// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fefwibupkqnejzmnhtqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlZndpYnVwa3FuZWp6bW5odHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjAzMzcsImV4cCI6MjA2NTI5NjMzN30.wEH2n8rAGxPN3G2Ol3qgkiNi6vE0yNMIBPnWc20Y1zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);